Allow build for Xcode versions prior Xcode 12
devxoul/Toaster pull request #200
Opened 2020-10-12 15:27 UTC by Niko-r

`.mac` case comes for iOS 14 with Xcode 12 & swift 5.3.

This allows the compilation with older Xcode versions (prior Xcode 12) that come with older an Swift compiler version.

2020-10-13 01:55 UTC, Coeur commented
Please use `#if compiler(>=5.3)` instead, as people can still use Swift 4 with Xcode 12.

2020-10-13 06:47 UTC, Coeur requested changes
Use `#if compiler(>=5.3)` instead.

2020-10-16 01:52 UTC, RioRizkyRainey approved these changes
look good to me

2020-10-17 15:18 UTC, Niko-r commented
Thank you both for your reviews. 

I’m fine with this change, I’ll do it once I’m back on a computer

2020-10-19 01:32 UTC, merged

2020-10-19 01:38 UTC, Coeur commented
I did the change from my iPhone.